### ISSUE TITLE
AbstractionConverter does not handle PropertyNamingPolicy is null in CreateObjectInstance

### ISSUE THREAD

**Issue by IngemarNilsson** [lwardzala/Json.Abstraction#3]
This setup is OK:

    options = new JsonSerializerOptions()
      {
        PropertyNameCaseInsensitive = true,
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonAbstractionConverter() }
      };

Setup that raises exception

    options = new JsonSerializerOptions()
      {
        PropertyNameCaseInsensitive = true,
        WriteIndented = true,
        //PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonAbstractionConverter() }
      };

Where it throws:

    namespace Json.Abstraction.Converters
    public class AbstractionConverter
    ....
    private object CreateObjectInstance(Type type, JsonElement jsonElement, JsonSerializerOptions options)
    {
        var instance = Activator.CreateInstance(type);
  
        type.GetProperties().ToList().ForEach(property =>
        {
            //throws when options.PropertyNamingPolicy is null
            var jsonPropertyName = options.PropertyNamingPolicy.ConvertName(property.Name);

StackTrace:

    Message: 
      System.NullReferenceException : Object reference not set to an instance of an object.
    Stack Trace: 
      <>c__DisplayClass4_0.<CreateObjectInstance>b__0(PropertyInfo property) line 64
      List`1.ForEach(Action`1 action)
      AbstractionConverter`1.CreateObjectInstance(Type type, JsonElement jsonElement, JsonSerializerOptions options) line 62
      AbstractionConverter`1.DeserializeAbstractObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) line 55
      AbstractionConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) line 23
      JsonPropertyInfoNotNullable`4.OnReadEnumerable(ReadStack& state, Utf8JsonReader& reader)
      JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
      JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
      JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
      JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
      JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
      JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)

**Comment by IngemarNilsson** [comment]
Great work by the way!

**Comment by lwardzala** [comment]
Thanks for rising the issue. I think I'll be able to release update with major fixes soon :)
